### ISSUE TITLE
JSA-2021-0004 - Log4J Patch

### ISSUE THREAD

**Issue by rsoika** [jitsi-contrib/jitsi-kubernetes#16]
See: https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2021-0005.md

Upgrade versions:

    stable-5870 => stable-6726

**Comment by rsoika** [comment]
Does anyone know if this version upgrade is sufficient? Or did we need to set additional environment variables?

**Comment by prayagsingh** [comment]
> Does anyone know if this version upgrade is sufficient? Or did we need to set additional environment variables?

Yes
