### ISSUE TITLE
updating docker-compose file

### ISSUE THREAD

**Issue by OverwhelmedStudent** [jitsi-contrib/jitsi-kubernetes#18]
Greetings, 
you explain "Change all ports to have a single number form instead of Port:Port form (using the environment variables) "

In the file I see those ports defined as ’${HTTP_PORT}:80' or '${JVB_PORT}:${JVB_PORT}/udp’ 
So how exactly are those supposed to look instead and what is added as environment variables?

**Comment by rsoika** [comment]
I recommand to use the [kustomize variant](https://github.com/jitsi-contrib/jitsi-kubernetes/tree/main/doc/kustomize) instead of kompose. 'kustomize'  is more easy to adapt jitsi into your kubernetes cluster. Just follow this [Install Guide](https://github.com/jitsi-contrib/jitsi-kubernetes/tree/main/doc/kustomize)

**Comment by OverwhelmedStudent** [comment]
Thank you for your fast answer, I will look into the deployment with kustomize.

I am working with Microk8s, are there special things to be aware of that differ to a normal kubernetes deployment?

**Comment by rsoika** [comment]
no, this should work fine with Microk8s

**Comment by marner2** [comment]
To answer the question posed originally, I meant to replace "${HTTP_PORT}:80" and "${JVB_PORT}:${JVB_PORT}/udp" to "${HTTP_PORT}" and "${JVB_PORT}/udp"

Is there a better way I can word that to make it clearer in the documentation?

**Comment by marner2** [comment]
I created #20 to clarify this for future. @OverwhelmedStudent does this clarify things?

**Comment by OverwhelmedStudent** [comment]
Yes, thank you!
I was able to advance here by comparing my files to the provided docker-compose.yml

**Comment by marner2** [comment]
Closing issue as it seems to be resolved.
