### ISSUE TITLE
Provide a Docker-Compose migration example

### ISSUE THREAD

**Issue by rsoika** [jitsi-contrib/jitsi-kubernetes#2]
Provide a example how to migrate from a existing Docker-Compose stack to kubernetes

**Comment by marner2** [comment]
#3 should address this. I want to fiddle with the wording a little, let me know what you find confusing about it, so we have an extra set of eyes.

**Comment by rsoika** [comment]
Thanks for your pull request. I have added you as a admin to this repo - so you should be able to commit directly - and don't need a pull request. 

I think for the moment we should just add working examples and tutorials into this repo. Your idea with the config-map sounds promising. If you take a look into the project [hpi-schul-cloud/jitsi-deployment](https://github.com/hpi-schul-cloud/jitsi-deployment) I think this is also an example using a configMap. 

For my (very simple) kustomize setup it seems not to be necessary for now.

**Comment by rsoika** [comment]
I reviewed the text and I think it is very good. I only added the heading and made minor changes to the introduction.
