### ISSUE TITLE
 websocket connect error after when joined meet

### ISSUE THREAD

**Issue by wpjscc** [jitsi-contrib/jitsi-kubernetes#22]
![image](https://user-images.githubusercontent.com/76907477/161993563-9b93c7a4-b126-4c87-9b1c-02d7d8b71b8d.png)

I do not know  where is error

I search the word [wss://localhost:8443/colibri-ws/127.0.0.1/](https://github.com/search?q=org%3Ajitsi+wss%3A%2F%2Flocalhost%3A8443%2Fcolibri-ws%2F127.0.0.1&type=issues) in the  https://github.com/jitsi

the result is not found

**Comment by damencho** [comment]
wrong jvb config

**Comment by wpjscc** [comment]
> wrong jvb config

thanks

**Comment by cheermao** [comment]
@wpjscc 
I happen the same error, do u solve it？
Is it the `DOCKER_HOST_ADDRESS`？

**Comment by Masterbr1an** [comment]
> @wpjscc I happen the same error, do u solve it？ Is it the `DOCKER_HOST_ADDRESS`？

i got the same error on eks. did you find a solution ?

**Comment by kskalski** [comment]
I think the instructions in https://github.com/jitsi-contrib/jitsi-kubernetes/tree/main/doc/kustomize are missing the necessary config for `jvb`, basically adding `PUBLIC_URL` also to its env override:
```
        - name: jvb
          env:
            - name: PUBLIC_URL
              value: "https://your.domain"
```

**Comment by lamthinhphat-kms** [comment]
how to fix this 

> > wrong jvb config
> 
> thanks
