### ISSUE TITLE
Unable to record Video during meeting

### ISSUE THREAD

**Issue by amitoo7** [jitsi-contrib/jitsi-kubernetes#9]
Hello, 

I am not able to record  meeting and i am supposing this may be because we are not installing jibri in our deployment. 
Any help to install jibri will be appreciated.

**Comment by prayagsingh** [comment]
Please follow the threads available on jitsi-community.

**Comment by amitoo7** [comment]
Sure, I'll follow with jitsi-community ofcourse but my question was are we planing to add jibri in this setup ?

**Comment by prayagsingh** [comment]
Sorry, No plans as of now.

**Comment by amitoo7** [comment]
Thanks @prayagsingh
